#include <iostream>
using namespace std;
main() {
    cout << "GRA KOLKO I KRZYZYK" << endl;
    cout << "AUTOR: MATEUSZ GUZOWSKI 1d" << endl;
    cout << "OPIS I INSTRUKCJE DOTYCZACE GRY:" << endl;
    cout << "GRA TA JEST PRZEZNACZONA DLA DWOCH OSOB. ZAWSZE GRE ROZPOCZYNA UZYTKOWNIK 1.\nSPRAWY Z TYM ZWIAZANE USTALAJA UZYTKOWNICY." << endl;
    cout << "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" << endl;











}
